packages:
  - apps/*
  - packages/*

ignoredBuiltDependencies:
  - protobufjs
  - unrs-resolver

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@tailwindcss/oxide"
  - core-js
  - esbuild
  - sharp
