name: llmgateway-unified

services:
  llmgateway:
    image: ghcr.io/theopenco/llmgateway-unified:latest
    container_name: llmgateway
    restart: unless-stopped
    ports:
      - "3002:3002" # UI
      - "3003:3003" # Playground
      - "3005:3005" # Docs
      - "4001:4001" # Gateway
      - "4002:4002" # API
      - "5432:5432" # PostgreSQL
      - "6379:6379" # Redis
    volumes:
      - llmgateway_postgres:/var/lib/postgresql/data
      - llmgateway_redis:/var/lib/redis
    environment:
      # URLs (update for your domain in production)
      - UI_URL=${UI_URL:-http://localhost:3002}
      - PLAYGROUND_URL=${PLAYGROUND_URL:-http://localhost:3003}
      - API_URL=${API_URL:-http://localhost:4002}
      - API_BACKEND_URL=${API_BACKEND_URL:-http://localhost:4002}
      - ORIGIN_URLS=${ORIGIN_URLS:-http://localhost:3002,http://localhost:3003,http://localhost:4002}
      - COOKIE_DOMAIN=${COOKIE_DOMAIN:-localhost}

      # Authentication
      - PASSKEY_RP_ID=${PASSKEY_RP_ID:-localhost}
      - PASSKEY_RP_NAME=${PASSKEY_RP_NAME:-LLMGateway}
      - AUTH_SECRET=${AUTH_SECRET:-your-secret-key}

      # Analytics (optional)
      - POSTHOG_KEY=${POSTHOG_KEY:-}
      - POSTHOG_HOST=${POSTHOG_HOST:-}

      # Stripe (optional)
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY:-}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET:-}
      - STRIPE_PRO_MONTHLY_PRICE_ID=${STRIPE_PRO_MONTHLY_PRICE_ID:-}
      - STRIPE_PRO_YEARLY_PRICE_ID=${STRIPE_PRO_YEARLY_PRICE_ID:-}

      # LLM Provider API Keys (add the ones you need)
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      - GOOGLE_AI_STUDIO_API_KEY=${GOOGLE_AI_STUDIO_API_KEY:-}

volumes:
  llmgateway_postgres:
    driver: local
  llmgateway_redis:
    driver: local
